export const GET_BOOKS_LOADING = "GET_BOOKS_LOADING";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAILURE = "GET_BOOKS_FAILURE";

export const ADD_BOOKS_LOADING = "ADD_BOOKS_LOADING";
export const ADD_BOOKS_SUCCESS = "ADD_BOOKS_SUCCESS";
export const ADD_BOOKS_FAILURE = "ADD_BOOKS_FAILURE";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
